name: Merge Packages Versions Upgrades PR

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * 1'

env:
  GIT_BRANCH_FOR_PACKAGES_UPGRADES: feature__packages_versions_update

jobs:
  merge_packages_versions_upgrades_pr_job:
    name: 'Check Packages Versions'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18']
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.AUTOMATION_GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/
      - name: Step 1 - ⚙️ Setup GitHub Config
        run: |
          git config user.name "🤖 DailyBot"
          git config user.email "ops@dailybot.com"
          gh auth login --with-token <<< "${{ secrets.AUTOMATION_GITHUB_TOKEN }}"
      - name: Step 2 - Check if there is any pr with packages upgrades available
        id: check_upgrades_available_pr_step
        run: |
          PR_NUMBER=$(gh pr list -B main -s open -L 1 --json number,headRefName -q '.[] | select(.headRefName == "feature__packages_versions_update") | .number')
          if [ -z "$PR_NUMBER" ]; then
            echo "No open PRs from feature__packages_versions_update to main"
            exit 0
          fi
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
      - if: ${{ steps.check_upgrades_available_pr_step.outputs.pr_number }}
        name: Step 3 - Check PR status, conclusion and mergeability
        id: check_pr_status_and_conclusion_step
        run: |
          PR_NUMBER="${{ steps.check_upgrades_available_pr_step.outputs.pr_number }}"
          echo "LOGS CHECKS"
          echo $PR_NUMBER

          PR_DATA=$(gh api repos/:owner/:repo/pulls/$PR_NUMBER)
          MERGEABLE_STATE=$(echo "$PR_DATA" | jq -r '.mergeable_state')

          if [ "$MERGEABLE_STATE" != "clean" ]; then
            echo "PR #$PR_NUMBER is not ready to be merged (Mergeable state: $MERGEABLE_STATE)"
            exit 0
          fi

          CHECKS_DATA=$(gh api repos/:owner/:repo/commits/$(gh pr view $PR_NUMBER --json headRefOid -q '.headRefOid')/check-runs)
          echo "$CHECKS_DATA" | jq -r '.check_runs[].conclusion' | while read -r CHECK_CONCLUSION; do
            if [ "$CHECK_CONCLUSION" != "success" ]; then
              echo "A check for PR #$PR_NUMBER has not succeeded"
              exit 0
            fi
          done

          echo "pr_checks_done='true'" >> $GITHUB_OUTPUT

    outputs:
      pr_number: ${{ steps.check_upgrades_available_pr_step.outputs.pr_number }}
      pr_checks_done: ${{ steps.check_pr_status_and_conclusion_step.outputs.pr_checks_done }}
